export const ROUTES = {
  root: '/',
  legacyDashboard: '/dashboard',
  appDashboard: '/app-dashboard',
  menu: '/menu',
  login: '/login',
  register: '/register',
  about: '/about',
  contact: '/contact',
  shop: '/shop',
  orderHistory: '/order-history',
  checkout: '/checkout',
  orderConfirmation: '/order-confirmation',
  orderTracking: '/order-tracking',
  userDashboard: '/user-dashboard',
  adminDashboard: '/admin-dashboard',
  adminOrders: '/admin/orders',
  reclamations: '/admin/reclamations',
  categories: '/categories',
  menus: '/menus',
  statistics: '/statistics',
  profile: '/profile',
} as const
